version: '3'

services:
  goflomainnet:
    build:
      context: go-flo
      dockerfile: Dockerfile
      args:
        network: mainnet
    hostname: goflomainnet
    ports:
      - "7316:7316"
      - "127.0.0.1:7317:7317"
    volumes:
      - goFloMainnetHome:/root/.flod/
    networks:
      - floMainnetNetwork

  goflotestnet:
    build:
      context: go-flo
      dockerfile: Dockerfile
      args:
        network: testnet
    hostname: goflotestnet
    ports:
      - "17316:17316"
      - "127.0.0.1:17317:17317"
    volumes:
      - goFloTestnetHome:/root/.flod/
    networks:
      - floTestnetNetwork

  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    volumes:
      - ./ipfsStaging:/export
      - ipfsData:/data/ipfs

  esmainnet:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    environment:
      - cluster.name=mainnet-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esMainnetData:/usr/share/elasticsearch/data
    networks:
      - esMainnetNetwork

  estestnet:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    environment:
      - cluster.name=testnet-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esTestnetData:/usr/share/elasticsearch/data
    networks:
      - esTestnetNetwork

  kibanamainnet:
    image: docker.elastic.co/kibana/kibana:7.17.8
    hostname: kibanaMainnet
    depends_on:
      - esmainnet
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - esMainnetNetwork
    environment:
      SERVER_HOST: 0.0.0.0
      # SERVER_BASEPATH: "/mainnet/kibana"
      # SERVER_REWRITEBASEPATH:
      ELASTICSEARCH_HOSTS: http://esmainnet:9200

  kibanatestnet:
    image: docker.elastic.co/kibana/kibana:7.17.8
    hostname: kibanaTestnet
    depends_on:
      - estestnet
    ports:
      - "127.0.0.1:15601:5601"
    networks:
      - esTestnetNetwork
    environment:
      SERVER_HOST: 0.0.0.0
      # SERVER_BASEPATH: "/testnet/kibana"
      # SERVER_REWRITEBASEPATH:
      ELASTICSEARCH_HOSTS: http://estestnet:9200

  oipmainnet:
    build:
      context: oip/
      dockerfile: Dockerfile
      args:
        network: mainnet
    depends_on:
      - goflomainnet
      - esmainnet
    ports:
      - "127.0.0.1:1606:1606"
    networks:
      - esMainnetNetwork
      - floMainnetNetwork
    volumes:
      - goFloMainnetHome:/flo/

  oiptestnet:
    build:
      context: oip/
      dockerfile: Dockerfile
      args:
        network: testnet
    depends_on:
      - goflotestnet
      - estestnet
    ports:
      - "127.0.0.1:11606:11606"
    networks:
      - esTestnetNetwork
      - floTestnetNetwork
    volumes:
      - goFloTestnetHome:/flo/

  webwallet:
    build: webwallet
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:7000:7000"


networks:
  esMainnetNetwork:
  esTestnetNetwork:
  floMainnetNetwork:
  floTestnetNetwork:

volumes:
  goFloMainnetHome:
  goFloTestnetHome:
  esTestnetData:
  esMainnetData:
  ipfsData:
