name: oip-webwallet

on:
  push:
    branches:
    - master
    paths:
    - 'webwallet/Dockerfile'
    - '.github/workflows/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build it
      run: docker build webwallet/ --tag opennetwork/oip-webwallet:latest
    
    - name: Push it
      run: docker push opennetwork/oip-webwallet:latest
    
